// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dplusC
RcppExport long double dplusC(NumericVector xx);
RcppExport SEXP RRSM_dplusC(SEXP xxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xx(xxSEXP);
    __result = Rcpp::wrap(dplusC(xx));
    return __result;
END_RCPP
}
// pairDiffs
RcppExport NumericVector pairDiffs(NumericVector A, NumericVector B);
RcppExport SEXP RRSM_pairDiffs(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    __result = Rcpp::wrap(pairDiffs(A, B));
    return __result;
END_RCPP
}
// pairSums
RcppExport NumericVector pairSums(NumericVector A, NumericVector B);
RcppExport SEXP RRSM_pairSums(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    __result = Rcpp::wrap(pairSums(A, B));
    return __result;
END_RCPP
}
// sig2dplusC
RcppExport long double sig2dplusC(NumericVector xx);
RcppExport SEXP RRSM_sig2dplusC(SEXP xxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xx(xxSEXP);
    __result = Rcpp::wrap(sig2dplusC(xx));
    return __result;
END_RCPP
}
// wtijloop
RcppExport NumericVector wtijloop(float cc, NumericVector ahat);
RcppExport SEXP RRSM_wtijloop(SEXP ccSEXP, SEXP ahatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< float >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ahat(ahatSEXP);
    __result = Rcpp::wrap(wtijloop(cc, ahat));
    return __result;
END_RCPP
}
