// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dplusC
RcppExport long double dplusC(NumericVector xx);
RcppExport SEXP _RRSM_dplusC(SEXP xxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xx(xxSEXP);
    rcpp_result_gen = Rcpp::wrap(dplusC(xx));
    return rcpp_result_gen;
END_RCPP
}
// pairDiffs
Rcpp::NumericVector pairDiffs(NumericVector A, NumericVector B);
RcppExport SEXP _RRSM_pairDiffs(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(pairDiffs(A, B));
    return rcpp_result_gen;
END_RCPP
}
// pairSums
Rcpp::NumericVector pairSums(Rcpp::NumericVector A, Rcpp::NumericVector B);
RcppExport SEXP _RRSM_pairSums(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(pairSums(A, B));
    return rcpp_result_gen;
END_RCPP
}
// sig2dplusC
RcppExport long double sig2dplusC(NumericVector xx);
RcppExport SEXP _RRSM_sig2dplusC(SEXP xxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xx(xxSEXP);
    rcpp_result_gen = Rcpp::wrap(sig2dplusC(xx));
    return rcpp_result_gen;
END_RCPP
}
// wtijloop
NumericVector wtijloop(float cc, NumericVector ahat);
RcppExport SEXP _RRSM_wtijloop(SEXP ccSEXP, SEXP ahatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ahat(ahatSEXP);
    rcpp_result_gen = Rcpp::wrap(wtijloop(cc, ahat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RRSM_dplusC", (DL_FUNC) &_RRSM_dplusC, 1},
    {"_RRSM_pairDiffs", (DL_FUNC) &_RRSM_pairDiffs, 2},
    {"_RRSM_pairSums", (DL_FUNC) &_RRSM_pairSums, 2},
    {"_RRSM_sig2dplusC", (DL_FUNC) &_RRSM_sig2dplusC, 1},
    {"_RRSM_wtijloop", (DL_FUNC) &_RRSM_wtijloop, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RRSM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
