# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dplusC <- function(xx) {
    .Call('RRSM_dplusC', PACKAGE = 'RRSM', xx)
}

pairDiffs <- function(A, B) {
    .Call('RRSM_pairDiffs', PACKAGE = 'RRSM', A, B)
}

pairSums <- function(A, B) {
    .Call('RRSM_pairSums', PACKAGE = 'RRSM', A, B)
}

sig2dplusC <- function(xx) {
    .Call('RRSM_sig2dplusC', PACKAGE = 'RRSM', xx)
}

wtijloop <- function(cc, ahat) {
    .Call('RRSM_wtijloop', PACKAGE = 'RRSM', cc, ahat)
}

