# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dplusC <- function(xx) {
    .Call('_RRSM_dplusC', PACKAGE = 'RRSM', xx)
}

pairDiffs <- function(A, B) {
    .Call('_RRSM_pairDiffs', PACKAGE = 'RRSM', A, B)
}

pairSums <- function(A, B) {
    .Call('_RRSM_pairSums', PACKAGE = 'RRSM', A, B)
}

sig2dplusC <- function(xx) {
    .Call('_RRSM_sig2dplusC', PACKAGE = 'RRSM', xx)
}

wtijloop <- function(cc, ahat) {
    .Call('_RRSM_wtijloop', PACKAGE = 'RRSM', cc, ahat)
}

